apiVersion: v1
kind: Service

metadata:
  name: week9-service

spec:
  selector:
    app: week9

  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30088

  type: NodePort